# ===============================================================
# AcademicPages original structure (restored)
# ===============================================================
locale: "en-US"
site_theme: "default"
title: "Xingjiang Lin (Bryce)"
title_separator: "-"
name: &name "Xingjiang Lin (Bryce)"
description: &description "M.S. Student in Artificial Intelligence | University at Buffalo"
url: "https://linxingjiang.github.io"
baseurl: ""
repository: "LinXingJiang/LinXingJiang.github.io"

# ===============================================================
# Author info
# ===============================================================
author:
  avatar: "profile.png"
  name: "Xingjiang Lin (Bryce)"
  bio: "Research-oriented M.S. student in AI, focusing on humanoid robotics, agentic intelligence, and large language models."
  location: "University at Buffalo, NY"
  employer: "University at Buffalo"
  email: "xingjiang.lin@buffalo.edu"
  googlescholar: "https://scholar.google.com/"
  github: "LinXingJiang"
  linkedin: "https://www.linkedin.com/in/xingjianglin"

# ===============================================================
# Collections
# ===============================================================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# ===============================================================
# Defaults
# ===============================================================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# ===============================================================
# Markdown and plugins
# ===============================================================
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# ===============================================================
# Output
# ===============================================================
permalink: /:categories/:title/
timezone: America/New_York

# ===============================================================
# Theme
# ===============================================================
remote_theme: "academicpages/academicpages.github.io"
