# ===============================================================
# Site Information
# ===============================================================
title: "Xingjiang Lin (Bryce)"
email: "xingjiang.lin@buffalo.edu"
description: "M.S. Student in Artificial Intelligence | University at Buffalo"
baseurl: "" # leave blank unless your site is in a subfolder
url: "https://linxingjiang.github.io"

# ===============================================================
# Author Profile
# ===============================================================
author:
  name: "Xingjiang Lin (Bryce)"
  avatar: "images/profile.jpg" # put your photo under /images/
  position: "Research M.S. Student in Artificial Intelligence"
  affiliation: "University at Buffalo, The State University of New York"
  email: "xingjiang.lin@buffalo.edu"
  bio: >
    I am a research-oriented master's student at the University at Buffalo focusing on humanoid robotics,
    agentic intelligence, and large language models. I have two years of software engineering experience,
    including at the London Stock Exchange Group (LSEG), where I contributed to scalable system design
    and intelligent automation solutions.

# ===============================================================
# Social Links
# ===============================================================
social:
  github: "LinXingJiang"
  linkedin: "https://www.linkedin.com/in/xingjianglin"
  scholar: "https://scholar.google.com/"
  email: "xingjiang.lin@buffalo.edu"
  cv: "/files/Xingjiang_Lin_CV.pdf"
  twitter: ""

# ===============================================================
# Theme & Plugins
# ===============================================================
remote_theme: "academicpages/academicpages.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# ===============================================================
# Site Settings
# ===============================================================
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: pretty
timezone: America/New_York
paginate: 5
paginate_path: "/page:num/"

# ===============================================================
# Navigation Bar
# ===============================================================
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
  - title: "Talks"
    url: /talks/
  - title: "Blog"
    url: /posts/
  - title: "CV"
    url: /files/Xingjiang_Lin_CV.pdf
  - title: "Contact"
    url: /contact/

# ===============================================================
# Collections (Academic Content)
# ===============================================================
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  projects:
    output: true
    permalink: /projects/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "talks"
    values:
      layout: talk
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# ===============================================================
# SEO & Analytics
# ===============================================================
seo:
  type: Person
  name: "Xingjiang Lin"
  same_as:
    - "https://github.com/LinXingJiang"
    - "https://www.linkedin.com/in/xingjianglin"
    - "https://scholar.google.com/"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXX-X" # optional
    anonymize_ip: true

# ===============================================================
# Exclude from Build
# ===============================================================
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - markdown_generator
