# ===============================================================
# Site information
# ===============================================================
title: "Xingjiang Lin (Bryce)"
description: "M.S. Student in Artificial Intelligence | University at Buffalo"
url: "https://xingjianglin.github.io"
baseurl: "" # leave empty unless using a subpath

# ===============================================================
# Author details
# ===============================================================
author:
  name: "Xingjiang Lin (Bryce)"
  position: "Research M.S. Student in Artificial Intelligence"
  affiliation: "University at Buffalo, The State University of New York"
  email: "xingjiang.lin@buffalo.edu"
  bio: >
    I am a research-oriented master's student at the University at Buffalo focusing on humanoid robotics,
    agentic intelligence, and large language models. I have two years of software engineering experience,
    including at the London Stock Exchange Group (LSEG), where I contributed to scalable system design
    and intelligent automation solutions.
  avatar: "/assets/img/profile.jpg"  # path to your portrait photo

# ===============================================================
# Social media
# ===============================================================
social:
  github: "xingjianglin"
  linkedin: "https://www.linkedin.com/in/xingjianglin"
  scholar: "https://scholar.google.com/"
  email: "xingjiang.lin@buffalo.edu"
  twitter: ""
  cv: "/files/Xingjiang_Lin_CV.pdf"

# ===============================================================
# Appearance and theme
# ===============================================================
remote_theme: "mmistakes/minimal-mistakes"
locale: "en-US"
skin: "default"

# ===============================================================
# Navigation bar
# ===============================================================
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
  - title: "Talks"
    url: /talks/
  - title: "Blog"
    url: /posts/
  - title: "CV"
    url: /files/Xingjiang_Lin_CV.pdf
  - title: "Contact"
    url: /contact/

# ===============================================================
# Collections (academic content)
# ===============================================================
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  projects:
    output: true
    permalink: /projects/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path/

# ===============================================================
# Markdown, math, syntax highlighting
# ===============================================================
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

# ===============================================================
# Plugins
# ===============================================================
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-archives

# ===============================================================
# Pagination
# ===============================================================
paginate: 5
paginate_path: "/page:num/"

# ===============================================================
# Defaults (layout configuration)
# ===============================================================
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "talks"
    values:
      layout: talk
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# ===============================================================
# SEO and analytics
# ===============================================================
seo:
  type: Person
  name: "Xingjiang Lin"
  same_as:
    - "https://github.com/xingjianglin"
    - "https://www.linkedin.com/in/xingjianglin"
    - "https://scholar.google.com/"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXX-X" # optional
    anonymize_ip: true

# ===============================================================
# Build settings
# ===============================================================
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# ===============================================================
# Sitemap
# ===============================================================
permalink: pretty
timezone: America/New_York
